---
- name: Install all the packages
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - httpd
    - mod_ssl
    - php
    - firewalld
- name: Ensure Apache and firewalld running
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - httpd
    - firewalld
- name: firewall is allowing traffic
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop:
    - "80/tcp"
    - "443/tcp"
- name: Index content
  template:
    src: index.html.j2
    dest:  /var/www/html/index.html
  notify: restart_apache
